CREATE DATABASE eventos_sostenibles;
USE eventos_sostenibles;

CREATE TABLE USUARIOS (
    Correo VARCHAR(200) PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Contrasena VARCHAR(200) NOT NULL
);

CREATE TABLE ORGANIZADORES (
    Usuario VARCHAR(200) PRIMARY KEY,
    Telefono CHAR(9),
    FOREIGN KEY (Usuario) REFERENCES USUARIOS(Correo)
);

CREATE TABLE CATEGORIA (
    Id_Categoria INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE UBICACIONES (
    Id_Ubicacion INT AUTO_INCREMENT PRIMARY KEY,
    Direccion VARCHAR(100) NOT NULL,
    Online BOOLEAN NOT NULL
);

CREATE TABLE EVENTOS (
    Id_Evento INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Fecha DATE NOT NULL,
    Duracion INT NOT NULL,
    Ubicacion INT NOT NULL,
    Categoria INT NOT NULL,
    Organizador VARCHAR(200) NOT NULL,
    FOREIGN KEY (Ubicacion) REFERENCES UBICACIONES(Id_Ubicacion),
    FOREIGN KEY (Categoria) REFERENCES CATEGORIA(Id_Categoria),
    FOREIGN KEY (Organizador) REFERENCES ORGANIZADORES(Usuario)
);

CREATE TABLE ASISTENTES (
    Evento INT NOT NULL,
    Usuario VARCHAR(200) NOT NULL,
    PRIMARY KEY (Evento, Usuario),
    FOREIGN KEY (Evento) REFERENCES EVENTOS(Id_Evento),
    FOREIGN KEY (Usuario) REFERENCES USUARIOS(Correo)
);
